version: '3.9'

services:
  redis:
    image: redis:7
    container_name: ldm_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: ldm_dashboard
    environment:
      - LDM_REDIS_HOST=redis
      - LDM_REDIS_PORT=6379
    ports:
      - "8501:8501"
    depends_on:
      - redis
    restart: unless-stopped
    command: streamlit run dashboard/streamlit_app.py --server.port=8501 --server.address=0.0.0.0

  slackbot:
    build:
      context: ./slack_bot_socket_mode
      dockerfile: Dockerfile
    container_name: ldm_slackbot
    env_file:
      - ./slack_bot_socket_mode/.env
    environment:
      - LDM_REDIS_HOST=redis
      - LDM_REDIS_PORT=6379
    depends_on:
      - redis
    restart: unless-stopped
    command: python app.py
